// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoyXvb8t6YFT2agIKsTxKdWZjxHAnpFw4',
    appId: '1:10953845070:android:fc870bf561d6bf0d2a561f',
    messagingSenderId: '10953845070',
    projectId: 'realtog-4b2e0',
    storageBucket: 'realtog-4b2e0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3zoto8fK5GxG7W7ztfaNDMZWTc3EwMXw',
    appId: '1:10953845070:ios:3165c1ef5e4d6ad52a561f',
    messagingSenderId: '10953845070',
    projectId: 'realtog-4b2e0',
    storageBucket: 'realtog-4b2e0.firebasestorage.app',
    iosClientId: '10953845070-k91j3a02jr53kqtbvqa14r4a745eds98.apps.googleusercontent.com',
    iosBundleId: 'com.example.realtog',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3zoto8fK5GxG7W7ztfaNDMZWTc3EwMXw',
    appId: '1:10953845070:ios:3165c1ef5e4d6ad52a561f',
    messagingSenderId: '10953845070',
    projectId: 'realtog-4b2e0',
    storageBucket: 'realtog-4b2e0.firebasestorage.app',
    iosClientId: '10953845070-k91j3a02jr53kqtbvqa14r4a745eds98.apps.googleusercontent.com',
    iosBundleId: 'com.example.realtog',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcN3CeRzIMVblwkvF8liVETl_ZZ668mNE',
    appId: '1:10953845070:web:4760a870352712712a561f',
    messagingSenderId: '10953845070',
    projectId: 'realtog-4b2e0',
    authDomain: 'realtog-4b2e0.firebaseapp.com',
    storageBucket: 'realtog-4b2e0.firebasestorage.app',
    measurementId: 'G-LB0NNQFYBL',
  );
}
